CREATE TABLE `sap_purchasing_info_record_pricing_condition_data`
(
    `PurchasingInfoRecord`             varchar(10) NOT NULL,
    `ConditionRecord`                  varchar(10) NOT NULL,
    `ConditionSequentialNumber`        varchar(2) NOT NULL,
    `ConditionValidityEndDate`         varchar(80) NOT NULL,
    `ConditionValidityStartDate`       varchar(80) DEFAULT NULL,
    `ConditionApplication`             varchar(2) DEFAULT NULL,
    `ConditionType`                    varchar(4) DEFAULT NULL,
	`CreatedByUser`                    varchar(12) DEFAULT NULL,
	`CreationDate`                     varchar(80) DEFAULT NULL,
	`ConditionTextID`                  varchar(10) DEFAULT NULL,
	`PricingScaleType`                 varchar(1) DEFAULT NULL,
	`PricingScaleBasis`                varchar(1) DEFAULT NULL,
	`ConditionScaleQuantity`           varchar(17) DEFAULT NULL,
	`ConditionScaleQuantityUnit`       varchar(3) DEFAULT NULL,
	`ConditionScaleAmount`             varchar(80) DEFAULT NULL,
	`ConditionScaleAmountCurrency`     varchar(5) DEFAULT NULL,
	`ConditionCalculationType`         varchar(1) DEFAULT NULL,
	`ConditionRateValue`               varchar(14) DEFAULT NULL,
	`ConditionRateValueUnit`           varchar(5) DEFAULT NULL,
	`ConditionQuantity`                varchar(6) DEFAULT NULL,
	`ConditionQuantityUnit`            varchar(3) DEFAULT NULL,
	`ConditionToBaseQtyNmrtr`          varchar(6) DEFAULT NULL,
	`ConditionToBaseQtyDnmntr`         varchar(6) DEFAULT NULL,
	`BaseUnit`                         varchar(3) DEFAULT NULL,
	`ConditionLowerLimit`              varchar(14) DEFAULT NULL,
	`ConditionUpperLimit`              varchar(14) DEFAULT NULL,
	`ConditionAlternativeCurrency`     varchar(5) DEFAULT NULL,
	`ConditionExclusion`               varchar(1) DEFAULT NULL,
	`ConditionIsDeleted`               tinyint(1) DEFAULT NULL,
	`AdditionalValueDays`              varchar(2) DEFAULT NULL,
	`FixedValueDate`                   varchar(80) DEFAULT NULL,
	`PaymentTerms`                     varchar(4) DEFAULT NULL,
	`CndnMaxNumberOfSalesOrders`       varchar(2) DEFAULT NULL,
	`MinimumConditionBasisValue`       varchar(17) DEFAULT NULL,
	`MaximumConditionBasisValue`       varchar(17) DEFAULT NULL,
	`MaximumConditionAmount`           varchar(16) DEFAULT NULL,
	`IncrementalScale`                 varchar(4) DEFAULT NULL,
	`PricingScaleLine`                 varchar(4) DEFAULT NULL,
	`ConditionReleaseStatus`           varchar(1) DEFAULT NULL,
    PRIMARY KEY (`PurchasingInfoRecord`, `ConditionRecord`, `ConditionSequentialNumber`, `ConditionValidityEndDate`),
    CONSTRAINT `SAPPurchasingInfoRecordPricingCondition_fk` FOREIGN KEY (`PurchasingInfoRecord`) REFERENCES `sap_purchasing_info_record_general_data` (`PurchasingInfoRecord`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
