CREATE TABLE `sap_purchasing_info_record_purchasing_organization_plant_data`
(
    `PurchasingInfoRecord`  varchar(10) NOT NULL,
    `PurchasingInfoRecordCategory`  varchar(1) NOT NULL,
    `PurchasingOrganization` varchar(4) NOT NULL,
    `Plant`                 varchar(4) NOT NULL,
    `Supplier`              varchar(10) DEFAULT NULL,
    `Material`              varchar(40) DEFAULT NULL,
    `MaterialGroup`         varchar(9) DEFAULT NULL,
    `PurgDocOrderQuantityUnit` varchar(3) DEFAULT NULL,
    `PurchasingGroup`       varchar(3) DEFAULT NULL,
    `MinimumPurchaseOrderQuantity` varchar(13) DEFAULT NULL,
    `StandardPurchaseOrderQuantity` varchar(13) DEFAULT NULL,
    `MaterialPlannedDeliveryDurn` varchar(3) DEFAULT NULL,
    `OverdelivTolrtdLmtRatioInPct` varchar(3) DEFAULT NULL,
    `UnderdelivTolrtdLmtRatioInPct` varchar(3) DEFAULT NULL,
    `UnlimitedOverdeliveryIsAllowed` tinyint(1) DEFAULT NULL,
    `LastReferencingPurchaseOrder` varchar(10) DEFAULT NULL,
    `LastReferencingPurOrderItem` varchar(5) DEFAULT NULL,
    `NetPriceAmount`        varchar(11) DEFAULT NULL,
    `MaterialPriceUnitQty`  varchar(5) DEFAULT NULL,
    `PurchaseOrderPriceUnit` varchar(5) DEFAULT NULL,
    `PriceValidityEndDate`  date DEFAULT NULL,
    `InvoiceIsGoodsReceiptBased` tinyint(1) DEFAULT NULL,
    `TaxCode`               varchar(2) DEFAULT NULL,
    `IncotermsClassification` varchar(3) DEFAULT NULL,
    `MaximumOrderQuantity`  varchar(13) DEFAULT NULL,
    `IsRelevantForAutomSrcg` varchar(1) DEFAULT NULL,
    `IsEvaluatedRcptSettlmtAllowed` tinyint(1) DEFAULT NULL,
    `IsPurOrderAllwdForInbDeliv` tinyint(1) DEFAULT NULL,
    `IsOrderAcknRqd`        tinyint(1) DEFAULT NULL,
    `IsMarkedForDeletion`   tinyint(1) DEFAULT NULL,
    PRIMARY KEY (`PurchasingInfoRecord`, `PurchasingInfoRecordCategory`, `PurchasingOrganization`, `Plant`)
    CONSTRAINT `SAPPurchasingInfoRecordPurchasingOrganizationPlantData_fk` FOREIGN KEY (`PurchasingInfoRecord`) REFERENCES `sap_purchasing_info_record_general_data` (`PurchasingInfoRecord`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
